"""
Database connection pool management.

Single source of truth for the async pool, LangGraph checkpointer and store,
and all application table schemas + CRUD helpers.

Tables owned here:
  - users          (identity, created on first Google login)
  - threads        (conversation metadata, one per LangGraph thread)
  - refresh_tokens (session management, rotated on every use)
"""
import hashlib
import secrets
from datetime import datetime, timezone

from psycopg_pool import AsyncConnectionPool
from langgraph.checkpoint.postgres.aio import AsyncPostgresSaver
from langgraph.store.postgres.aio import AsyncPostgresStore


_pool: AsyncConnectionPool | None = None
_checkpointer: AsyncPostgresSaver | None = None
_store: AsyncPostgresStore | None = None


# ---------------------------------------------------------------------------
# Lifecycle
# ---------------------------------------------------------------------------

async def setup_database(database_url: str) -> None:
    """
    Initialize DB pool, run LangGraph migrations, and create app tables.
    Call once on startup — before compiling the workflow graph.
    """
    global _pool, _checkpointer, _store

    _pool = AsyncConnectionPool(
        conninfo=database_url,
        open=False,
        kwargs={"autocommit": True, "prepare_threshold": 0},
    )

    _checkpointer = AsyncPostgresSaver(_pool)
    _store        = AsyncPostgresStore(_pool)

    await _pool.open()
    await _checkpointer.setup()
    await _store.setup()
    await _create_app_tables()


async def teardown_database() -> None:
    """Close DB pool. Call on shutdown."""
    global _pool
    if _pool:
        await _pool.close()


# ---------------------------------------------------------------------------
# Accessors
# ---------------------------------------------------------------------------

def get_pool() -> AsyncConnectionPool:
    if _pool is None:
        raise RuntimeError("Database not initialized")
    return _pool


def get_checkpointer() -> AsyncPostgresSaver:
    if _checkpointer is None:
        raise RuntimeError("Database not initialized")
    return _checkpointer


def get_store() -> AsyncPostgresStore:
    if _store is None:
        raise RuntimeError("Database not initialized")
    return _store


# ---------------------------------------------------------------------------
# App table migrations
# ---------------------------------------------------------------------------

async def _create_app_tables() -> None:
    """
    Create all application-owned tables in dependency order.
    users must exist before threads and refresh_tokens (FK constraint).
    """
    async with _pool.connection() as conn:

        # ── users ──────────────────────────────────────────────────────────
        # user_id    : your internal UUID, used in JWTs and across all tables
        # google_sub : Google's stable user identifier — upsert conflict target
        #              never changes even if the user changes their email
        # email      : stored for display, refreshed on every login
        # name       : refreshed on every login via upsert
        # avatar_url : Google profile picture, refreshed on every login
        # created_at : account age is useful — kept here unlike threads table
        await conn.execute("""
            CREATE TABLE IF NOT EXISTS users (
                user_id     UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
                google_sub  TEXT        UNIQUE NOT NULL,
                email       TEXT        UNIQUE NOT NULL,
                name        TEXT        NOT NULL,
                avatar_url  TEXT,
                created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
        """)

        # ── threads ────────────────────────────────────────────────────────
        # thread_id  : UUIDv7 generated by caller — primary key + creation time
        # user_id    : FK to users, cascade delete removes threads with the user
        # updated_at : bumped conditionally — only if not already most recent thread
        #              see db_touch_thread for the optimized conditional update
        await conn.execute("""
            CREATE TABLE IF NOT EXISTS threads (
                thread_id   TEXT        PRIMARY KEY,
                user_id     UUID        NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
                updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
        """)

        # Covering index — list_threads query is index-only, never touches table rows
        # (user_id, updated_at DESC) for range scan + ordering
        # INCLUDE (thread_id) eliminates heap fetch for the SELECT
        await conn.execute("""
            CREATE INDEX IF NOT EXISTS idx_threads_last_active
                ON threads (user_id, updated_at DESC)
                INCLUDE (thread_id)
        """)

        # ── refresh_tokens ─────────────────────────────────────────────────
        # token_hash : SHA-256 of raw token — raw value never stored
        # user_id    : FK to users, cascade delete revokes all sessions on user removal
        # expires_at : checked on every refresh attempt
        # created_at : useful for audit and anomaly detection
        await conn.execute("""
            CREATE TABLE IF NOT EXISTS refresh_tokens (
                token_hash  TEXT        PRIMARY KEY,
                user_id     UUID        NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
                expires_at  TIMESTAMPTZ NOT NULL,
                created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
        """)

# ---------------------------------------------------------------------------
# Users CRUD
# ---------------------------------------------------------------------------

async def db_upsert_user(
    google_sub: str,
    email: str,
    name: str,
    avatar_url: str | None,
) -> dict:
    """
    Insert a new user or refresh name/avatar/email for a returning user.

    Conflict target is google_sub — stable across Google profile changes.
    user_id is never touched on update so all existing JWTs stay valid.
    RETURNING gives back the row in one query — no second lookup needed.
    """
    async with _pool.connection() as conn:
        async with conn.cursor() as cur:
            await cur.execute(
                """
                INSERT INTO users (google_sub, email, name, avatar_url)
                VALUES (%s, %s, %s, %s)
                ON CONFLICT (google_sub) DO UPDATE
                    SET name       = EXCLUDED.name,
                        avatar_url = EXCLUDED.avatar_url,
                        email      = EXCLUDED.email
                RETURNING user_id, email, name, avatar_url
                """,
                (google_sub, email, name, avatar_url),
            )
            row = await cur.fetchone()

    return {
        "user_id":    str(row[0]),
        "email":      row[1],
        "name":       row[2],
        "avatar_url": row[3],
    }


async def db_get_user(user_id: str) -> dict | None:
    """Fetch a user by their internal user_id. Returns None if not found."""
    async with _pool.connection() as conn:
        async with conn.cursor() as cur:
            await cur.execute(
                """
                SELECT user_id, email, name, avatar_url, created_at
                FROM users
                WHERE user_id = %s
                """,
                (user_id,),
            )
            row = await cur.fetchone()

    if row is None:
        return None
    return {
        "user_id":    str(row[0]),
        "email":      row[1],
        "name":       row[2],
        "avatar_url": row[3],
        "created_at": row[4],
    }


# ---------------------------------------------------------------------------
# Threads CRUD
# ---------------------------------------------------------------------------

async def db_create_thread(thread_id: str, user_id: str) -> dict:
    """
    Insert a new thread row.
    thread_id is UUIDv7 generated by the caller — encodes creation time.
    """
    async with _pool.connection() as conn:
        async with conn.cursor() as cur:
            await cur.execute(
                """
                INSERT INTO threads (thread_id, user_id)
                VALUES (%s, %s)
                RETURNING thread_id, user_id, updated_at
                """,
                (thread_id, user_id),
            )
            row = await cur.fetchone()

    return {
        "thread_id":  row[0],
        "user_id":    str(row[1]),
        "updated_at": row[2],
    }


async def db_get_thread(thread_id: str) -> dict | None:
    """
    Fetch a single thread by primary key.
    O(log n) — direct primary key lookup.
    """
    async with _pool.connection() as conn:
        async with conn.cursor() as cur:
            await cur.execute(
                """
                SELECT thread_id, user_id, updated_at
                FROM threads
                WHERE thread_id = %s
                """,
                (thread_id,),
            )
            row = await cur.fetchone()

    if row is None:
        return None
    return {
        "thread_id":  row[0],
        "user_id":    str(row[1]),
        "updated_at": row[2],
    }


async def db_list_threads(user_id: str) -> list[dict]:
    """
    Return all threads for a user ordered by most recently active.
    Index-only scan via idx_threads_last_active — never touches the table.
    """
    async with _pool.connection() as conn:
        async with conn.cursor() as cur:
            await cur.execute(
                """
                SELECT thread_id, user_id, updated_at
                FROM threads
                WHERE user_id = %s
                ORDER BY updated_at DESC
                """,
                (user_id,),
            )
            rows = await cur.fetchall()

    return [
        {
            "thread_id":  r[0],
            "user_id":    str(r[1]),
            "updated_at": r[2],
        }
        for r in rows
    ]


async def db_touch_thread(thread_id: str, user_id: str) -> None:
    """
    Bump updated_at only if this thread is not already the most recent one
    for this user. If it is already first, ordering won't change — skip the write.

    Both the subquery and the outer UPDATE use indexes — O(log n) total.
    The subquery is uncorrelated so Postgres executes it once, not per row.
    One round trip, one conditional write.
    """
    async with _pool.connection() as conn:
        await conn.execute(
            """
            UPDATE threads
            SET updated_at = NOW()
            WHERE thread_id = %s
            AND thread_id != (
                SELECT thread_id FROM threads
                WHERE user_id = %s
                ORDER BY updated_at DESC
                LIMIT 1
            )
            """,
            (thread_id, user_id),
        )


async def db_delete_thread(thread_id: str) -> bool:
    """
    Delete a thread metadata row.
    Returns True if a row was deleted, False if thread was not found.

    Note: LangGraph checkpoint data lives in its own tables and is not
    deleted here — no public API for that yet.
    """
    async with _pool.connection() as conn:
        async with conn.cursor() as cur:
            await cur.execute(
                "DELETE FROM threads WHERE thread_id = %s RETURNING thread_id",
                (thread_id,),
            )
            row = await cur.fetchone()
    return row is not None


# ---------------------------------------------------------------------------
# Refresh token CRUD
# ---------------------------------------------------------------------------

def _hash_token(raw_token: str) -> str:
    """SHA-256 hash of a raw token. Always store and compare hashes, never raw."""
    return hashlib.sha256(raw_token.encode()).hexdigest()


async def db_create_refresh_token(user_id: str, expires_at: datetime) -> str:
    """
    Generate a cryptographically random refresh token, store its hash,
    and return the raw token to be sent to the client via HttpOnly cookie.

    The raw token is never stored — only the hash. A breached DB is useless
    without the raw values.
    """
    raw_token  = secrets.token_urlsafe(64)
    token_hash = _hash_token(raw_token)

    async with _pool.connection() as conn:
        await conn.execute(
            """
            INSERT INTO refresh_tokens (token_hash, user_id, expires_at)
            VALUES (%s, %s, %s)
            """,
            (token_hash, user_id, expires_at),
        )

    return raw_token  # caller puts this in the HttpOnly cookie


async def db_rotate_refresh_token(
    raw_token: str,
    expires_at: datetime,
) -> tuple[str, str] | None:
    """
    Validate and rotate a refresh token in one operation:
      1. Hash the incoming raw token
      2. Look it up — missing means invalid or already rotated (reuse detected)
      3. Check expiry
      4. Delete the old token
      5. Insert a fresh token for the same user
      6. Return (user_id, new_raw_token)

    Returns None if the token is invalid or expired.
    Rotation means each token is single-use — reuse is detected immediately.
    """
    token_hash = _hash_token(raw_token)
    now        = datetime.now(timezone.utc)

    async with _pool.connection() as conn:
        async with conn.cursor() as cur:

            await cur.execute(
                """
                SELECT user_id, expires_at
                FROM refresh_tokens
                WHERE token_hash = %s
                """,
                (token_hash,),
            )
            row = await cur.fetchone()

            if row is None:
                return None  # not found — never existed or already rotated

            user_id      = str(row[0])
            token_expiry = row[1]

            if token_expiry.replace(tzinfo=timezone.utc) < now:
                return None  # expired

            # Delete old token
            await cur.execute(
                "DELETE FROM refresh_tokens WHERE token_hash = %s",
                (token_hash,),
            )

            # Issue new token
            new_raw   = secrets.token_urlsafe(64)
            new_hash  = _hash_token(new_raw)

            await cur.execute(
                """
                INSERT INTO refresh_tokens (token_hash, user_id, expires_at)
                VALUES (%s, %s, %s)
                """,
                (new_hash, user_id, expires_at),
            )

    return user_id, new_raw


async def db_delete_refresh_token(raw_token: str) -> None:
    """Delete a single refresh token — used on logout."""
    token_hash = _hash_token(raw_token)
    async with _pool.connection() as conn:
        await conn.execute(
            "DELETE FROM refresh_tokens WHERE token_hash = %s",
            (token_hash,),
        )


async def db_delete_all_user_tokens(user_id: str) -> None:
    """
    Revoke all sessions for a user.
    Used when suspicious activity is detected or user requests logout
    from all devices.
    """
    async with _pool.connection() as conn:
        await conn.execute(
            "DELETE FROM refresh_tokens WHERE user_id = %s",
            (user_id,),
        )